### ISSUE TITLE
Handle response with Transfer-Encoding: chunked header gracefully.

### ISSUE THREAD

**Issue by westoque** [ncr/rack-proxy#51] opened 2015-04-07 03:02 UTC
Right now, it just passes through, although Rack::Lint shows a warning. There is a streaming api however, and we should use it or suggest to use it when this happens.

Using:

rack-proxy - 0.5.17

Reproduce:

1. Proxy request to site with `Transfer-Encoding: chunked` header.
2. Get incomplete response rendered in browser.

What should happen:

We should get the complete response rendered in browser.

**Comment by timting** [comment] 2015-04-14 19:15
I'm experiencing this too. Does anyone have any pointers as to how we could fix this up?

**Comment by westoque** [comment] 2015-04-14 22:34
@timting Actually, my problem before was proxying from https -> http. If this is also true with your setup. Then you can solve this by doing forcing the request to use http.

```
env["HTTP_X_FORWARDED_PROTO"] = "http"
env["HTTP_X_FORWARDED_PORT"] = "80"
```

**Comment by twinge** [comment] 2016-03-24 23:38
I'm having this problem as well, and it's not an issue with the HTTP_X_FORWARDED_PROTO. Anyone come up with any ideas? @timting?

**Comment by twinge** [comment] 2016-03-24 23:42
Just noticed this appears to be a duplicate of #50

**Comment by ncr** [comment] 2016-05-17 22:36
Yup. Closing.

**Closed by ncr** 2016-05-17 22:36 UTC
